language: node_js
node_js:
- '11'
notifications:
  email:
    on_success: change
    on_failure: always
dist: xenial
jobs:
  include:
  - script:
    - npm run lint
    - npm run build-slow
    - npm run test:coverage
    - npm run coveralls
  - stage: SauceLabs
    if: "(branch = master) AND (NOT (type IN (pull_request)))"
    script:
    - npm run build:es
    - npm run build:es:dev
    - npm run test:browser:sauce
addons:
  sauce_connect:
    username: "renoken"
    access_key: "a6d4348d-c59e-46fe-8bbf-6f219f090e1b"
