language: node_js
node_js:
- '11'
notifications:
  email:
    on_success: change
    on_failure: always
dist: xenial
jobs:
  include:
  - script:
    - npm run lint
    - npm run build-slow
    - npm run test:coverage
    - npm run codecov
